import { StyleSheet, Font } from '@react-pdf/renderer';
Font.register({
  family: 'Open Sans',
  fonts: [
    { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },
    { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-600.ttf', fontWeight: 600 },
  ],
});
const borderColor = '#90e5fc';
export const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: 'row',
    marginTop: 24,
    marginBottom: 0,
    width: 'auto',
    justifyContent: 'space-around',
  },
  reportTitle: {
    color: 'black',
    letterSpacing: 1,
    fontSize: 20,
    textAlign: 'left',
  },
  reportTitle1: {
    fontFamily: 'Open Sans',
    color: 'black',
    fontSize: 10,
    textAlign: 'left',
    fontWeight: 600,
  },
  reportTitle2: {
    fontFamily: 'Open Sans',
    color: 'black',
    letterSpacing: 1,
    fontSize: 10,
    textAlign: 'left',
  },
  decorate: {
    flexDirection: 'row',
  },
  descDecorate: {
    width: '85%',
    textAlign: 'left',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    paddingLeft: 8,
  },
  description2: {
    fontFamily: 'Open Sans',
    width: '85%',
    textAlign: 'left',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    paddingLeft: 8,
    fontWeight: 'normal',
    fontSize: 10,
  },
  descriptionBold: {
    // bold
    fontFamily: 'Open Sans',
    width: '85%',
    textAlign: 'left',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    paddingLeft: 8,
    fontWeight: 'bold',
    fontSize: 10,
  },
  row: {
    fontFamily: 'Open Sans',
    flexDirection: 'row',
    borderBottomColor: '#bff0fd',
    borderBottomWidth: 1,
    alignItems: 'center',
    height: 24,
    fontSize: 11,
    fontStyle: 'bold',
    justifyContent: 'space-evenly',
  },
  row2: {
    flexDirection: 'row',
    borderBottomColor: '#bff0fd',
    borderBottomWidth: 1,
    alignItems: 'center',
    height: 24,
    justifyContent: 'space-between',
  },
  titleContainer1: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 0,
    width: 'auto',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  name: {
    width: '20%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  dob: {
    width: '15%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  email: {
    width: '25%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  signature: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  photoId: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  attendance: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
    textAlign: 'left',
    paddingLeft: 5,
  },
  expdt: {
    width: '20%',
    textAlign: 'left',
    paddingLeft: 5,
  },
  container: {
    flexDirection: 'row',
    borderBottomColor: '#bff0fd',
    backgroundColor: '#bff0fd',
    borderBottomWidth: 1,
    alignItems: 'center',
    height: 30,
    textAlign: 'center',
    fontStyle: 'bold',
    flexGrow: 1,
  },
  tableContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#bff0fd',
  },
  nameH: {
    width: '20%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  dobH: {
    width: '15%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  emailH: {
    width: '25%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  signatureH: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  photoIdH: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  attendanceH: {
    width: '10%',
    borderRightColor: borderColor,
    borderRightWidth: 1,
  },
  expdtH: {
    width: '20%',
  },
  fixed: {
    fontStyle: 'italic',
  },
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    paddingTop: 30,
    paddingLeft: 60,
    paddingRight: 60,
    lineHeight: 1.5,
    flexDirection: 'column',
  },
  logo: {
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  image: {
    width: '40%',
    height: '90%',
  },
  pageTile: {
    width: '100%',
  },
});
